language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make
  - if test "${TRAVIS_OS_NAME}" = "linux"; then
      make distcheck;
    else
      make check;
    fi
    || { cat test/test-suite.log; false; }

## whitelist
branches:
  only:
    - master

notifications:
  email:
    - devel@fresse.org
