language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make
  - make distcheck || { cat test/test-suite.log; false; }

## whitelist
branches:
  only:
    - master

notifications:
  email:
    - devel@fresse.org
